In [6]:
import pandas as pd
import psycopg2

In [28]:
assets_universe = pd.read_csv("../Database/data_ingestion/assets_universe.csv")
assets_universe

  ticker asset_type
0   AAPL     equity
1   TSLA     equity

In [29]:
assets_universe.loc[len(assets_universe)] = ['GOOGL', 'equity']
assets_universe

  ticker asset_type
0   AAPL     equity
1   TSLA     equity
2  GOOGL     equity

In [30]:
assets_universe.to_csv("../Database/data_ingestion/assets_universe.csv", index=False)
assets_universe = pd.read_csv("../Database/data_ingestion/assets_universe.csv")
assets_universe

  ticker asset_type
0   AAPL     equity
1   TSLA     equity
2  GOOGL     equity