In [1]:
import pandas as pd

## Assets Universe

In [2]:
assets_universe = pd.read_csv("../Database/data_ingestion/assets_universe.csv")
assets_universe

  ticker asset_type
0   AAPL     equity
1   TSLA     equity
2  GOOGL     equity
3    SPY        etf

In [3]:
# ADD NEW ASSET - uncomment here and add a new asset along with its info - be carefull 
# when adding columns -> the number of columns you input here must be the same number of 
#columns the df accepts

#assets_universe.loc[len(assets_universe)] = ['SPY', 'etf']
#assets_universe

In [4]:
assets_universe.to_csv("../Database/data_ingestion/assets_universe.csv", index=False)
assets_universe = pd.read_csv("../Database/data_ingestion/assets_universe.csv")
assets_universe

  ticker asset_type
0   AAPL     equity
1   TSLA     equity
2  GOOGL     equity
3    SPY        etf

## Rates Universe

In [5]:
rates_universe = pd.read_csv("../Database/data_ingestion/rates_universe.csv")
rates_universe

                  name ticker country currency                     unit
0  US 3M Treasury Bill   ^IRX      US      USD  annual_percentage_yield

In [6]:
# ADD NEW RATE - uncomment here and add a new rate along with its info - be carefull 
# when adding columns -> the number of columns you input here must be the same number of 
#columns the df accepts

#rates_universe.loc[len(rates_universe)] = ['US 3M Treasury Bill', '^IRX', 'US', 'USD', 'annual_percentage_yield']
#rates_universe

In [7]:
rates_universe.to_csv("../Database/data_ingestion/rates_universe.csv", index=False)
rates_universe = pd.read_csv("../Database/data_ingestion/rates_universe.csv")
rates_universe

                  name ticker country currency                     unit
0  US 3M Treasury Bill   ^IRX      US      USD  annual_percentage_yield